<a href="https://colab.research.google.com/github/demsaid400-cpu/DI_BOOTCAMP/blob/main/Week3_Day1_ExercicesXP_1_to_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

arr = np.arange(10)

print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [19]:
import numpy as np

data = [3.14, 2.17, 0, 1, 2]
arr = np.array(data)
arr_int = arr.astype(int)
print("Tableau converti :", arr_int)

arr_matrix = np.arange(1, 10).reshape(3, 3)
print("Matrice 3x3 :\n", arr_matrix)
import numpy as np

arr = np.random.rand(4, 5)

print(arr)
import numpy as np

array = np.array([
    [21, 22, 23, 22, 22],
    [20, 21, 22, 23, 24],
    [21, 22, 23, 22, 22]
])

second_row = array[1]

print(second_row)
import numpy as np

arr = np.arange(10)

reversed_arr = arr[::-1]

print(reversed_arr)
import numpy as np

identity_matrix = np.eye(4)

print(identity_matrix)
import numpy as np

arr = np.arange(10)

total_sum = np.sum(arr)
average = np.mean(arr)

print(f"Sum: {total_sum}, Average: {average}")
import numpy as np

arr = np.arange(1, 21)

reshaped_arr = arr.reshape(4, 5)

print(reshaped_arr)
import numpy as np

arr = np.arange(10)

odd_numbers = arr[arr % 2 == 1]

print(odd_numbers)

Tableau converti : [3 2 0 1 2]
Matrice 3x3 :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0.7615186  0.07106724 0.88755128 0.8546756  0.88020089]
 [0.05891699 0.85993959 0.65607107 0.56543799 0.75609184]
 [0.91305042 0.69093156 0.61906293 0.65927442 0.94073359]
 [0.8215658  0.89175134 0.38036379 0.5607871  0.10184732]]
[20 21 22 23 24]
[9 8 7 6 5 4 3 2 1 0]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Sum: 45, Average: 4.5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[1 3 5 7 9]
